// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL9z3IYmrjS8bd-I61qA0CveonfWgIOrs',
    appId: '1:450726471762:web:5e28b53e0b59f038f9178b',
    messagingSenderId: '450726471762',
    projectId: 'my-firebase-9b1d9',
    authDomain: 'my-firebase-9b1d9.firebaseapp.com',
    storageBucket: 'my-firebase-9b1d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYMZMDr3AF-RWSrN44kGGss5v0_7sLCUo',
    appId: '1:450726471762:android:4b19e2b57db294c0f9178b',
    messagingSenderId: '450726471762',
    projectId: 'my-firebase-9b1d9',
    storageBucket: 'my-firebase-9b1d9.appspot.com',
  );
}
